#ifndef SERVICE_BT_MUSIC_H_INCLUDED
#define SERVICE_BT_MUSIC_H_INCLUDED


#if defined(DATA_STRUCTURE_STREAM_CACHE) && (DATA_STRUCTURE_STREAM_CACHE == 1)



#endif // DATA_STRUCTURE_STREAM_CACHE


#endif // SERVICE_BT_MUSIC_H_INCLUDED
